version: '2.4'
services:
  intelligence-hub:
    image: highbyte:4.4.1
    expose:
      - 45245
    volumes:
      - 'hb_vol-441:/usr/local/highbyte/appData'
      - 'config_vol:/usr/local/highbyte/configuration/config'
      - './cfg-data:/cfg-data'
    entrypoint:
      - /bin/sh
      - -c
      - |
        EULA_FILE="/cfg-data/accept-eula.json"
        cat /cfg-data/accept-eula.json

        if [ ! -f "$$EULA_FILE" ]; then
          echo "ERROR: EULA file not found at $EULA_FILE"
          exit 0
        fi

        CONTENT=$(cat "$$EULA_FILE" | tr -d '[:space:]')
        echo $$CONTENT

        if [ "$$CONTENT" != '{"acceptEula":true}' ]; then
          echo "ERROR: You must accept the EULA before running Intelligence Hub."
          exit 0
        fi

        echo "EULA accepted, starting Intelligence Hub..."
        exec /usr/local/highbyte/runtime/entrypoint.sh "$$@"
      - --
    command: start
    restart: on-failure:3
    mem_limit: 1024m
    networks:
      - proxy-redirect
 
volumes:
  hb_vol-441:
  config_vol:
 
networks:
  proxy-redirect:
    external: true
